// <auto-generated />
using System;
using Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Datos.Migrations
{
    [DbContext(typeof(PersonasContext))]
    [Migration("20200520024538_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entity.Apoyo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModalidadApoyo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Persona")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ValorApoyo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Apoyos");
                });

            modelBuilder.Entity("Entity.Persona", b =>
                {
                    b.Property<string>("IdentificacionP")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApellidosP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CiudadP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartamentoP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EdadP")
                        .HasColumnType("int");

                    b.Property<string>("NombresP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SexoP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ValorAcumuladoApoyo")
                        .HasColumnType("int");

                    b.HasKey("IdentificacionP");

                    b.ToTable("Personas");
                });
#pragma warning restore 612, 618
        }
    }
}
